name: $(Date:yyyyMMdd).$(Rev:r)
variables:
  MAKE_VERBOSE: "0" # "0" or "1"
  MAKE_PLATFORM: "vpp"
  MAKE_TAG: "vpp" # "vpp" or "vpp_debug"
  GIT_VPP_URL: "https://github.com/FDio/vpp.git"  # if using https://gerrit.fd.io/r/vpp, VPP_BRANCH should be something like 'tag/v20.01'
  GIT_VPPSB_URL: "https://gerrit.fd.io/r/vppsb"

trigger:
  batch: true
  branches:
    include: [ "master" ]
  paths:
    exclude: [ "README.md", "LICENSE" ]

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
    always: true

jobs:
  - job: build
    displayName: "build"
    pool:
      vmImage: "ubuntu-latest"
    # container:
    #   image: "$(CONTAINER)"
    #   options: --user 0
    workspace:
      clean: all
    timeoutInMinutes: 120

    strategy:
      matrix:
        debian-11-vpp-latest:
          CONTAINER: 'debian:bullseye-slim'
          VPP_BRANCH: 'master'
        debian-10-vpp-2202:
          CONTAINER: 'debian:buster-slim'
          VPP_BRANCH: 'stable/2202'

    steps:
    - bash: './build.sh'
      displayName: 'build'

    - bash: |
        # recursive intentionally disabled
        cp vpp/build-root/* ${BUILD_ARTIFACTSTAGINGDIRECTORY}
        exit 0
      displayName: "copy artifacts"
      condition: always()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        artifactName: '$(System.JobName)'
        parallel: true
        ParallelCount: 8
      condition: always()
